
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family ="JetBrainsMono NF", style="Regular"}
bold = { family ="JetBrainsMono NF", style="Bold"}
italic = { family ="JetBrainsMono NF", style="Italic"}
bold_italic = { family ="JetBrainsMono NF", style="Bold Italic"}
size = 12


